# 1850
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Enkel Sample API

Resources:
  API:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionBody:
        swagger: 2.0
        info:
          title: !Join [ "-", [ Ref: "AWS::StackName", "API" ] ]
        schemes:
        - https
        paths:
          /geohash:
            get:
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${geohash.Arn}/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
            options:
              consumes:
              - application/json
              produces:
              - application/json
              responses:
                '200':
                  description: 200 response
                  schema:
                    $ref: "#/definitions/Empty"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Headers:
                      type: string
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Methods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
                      method.response.header.Access-Control-Allow-Headers: "'channel,Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token,x-strackid,region,language'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                passthroughBehavior: when_no_match
                requestTemplates:
                  application/json: "{\"statusCode\": 200}"
                type: mock
      StageName: LIVE

  customDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !ImportValue certificate
      DomainName:
        Fn::Join:
          - '.'
          - - api
            - !ImportValue zoneName
  
  dnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name:
        Fn::Join:
          - '.'
          - - api
            - !ImportValue zoneName
      HostedZoneId: !ImportValue zoneId
      AliasTarget:
        HostedZoneId: !GetAtt customDomain.DistributionHostedZoneId
        DNSName: !GetAtt customDomain.DistributionDomainName
      Type: A

  basePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref customDomain
      BasePath: antigravity
      RestApiId: !Ref API
      Stage: LIVE

  geohash:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Join:
         - '-'
         - - Ref: AWS::StackName
           - geohash
      Handler: handler.handler
      CodeUri: ./src
      Runtime: python3.7
      MemorySize: 128
      Timeout: 3
      Role: !ImportValue lambdaRole
      Events:
        geohash:
          Type: Api
          Properties:
            Path: /geohash
            Method: get
            RestApiId: !Ref API
  
  cognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: antigravity
  
  cognitoDomain:
    Type: "AWS::CloudFormation::CustomResource"
    Properties:
      ServiceToken: 
        !ImportValue cognitoUserPoolDomainResource
      Domain: antigravity
      UserPoolId: !Ref cognitoUserPool
  
  resourceServer:
    Type: "AWS::CloudFormation::CustomResource"
    Properties:
      ServiceToken: 
        !ImportValue cognitoServerResource
      user_pool_id: !Ref cognitoUserPool
      identifier: resource-antigravity
      name: resource-antigravity
      scope_list:
        - ScopeName: geohash.get
          ScopeDescription: Get Operations
  
  appClientCustom:
    Type: "AWS::CloudFormation::CustomResource"
    Properties:
      ServiceToken: 
        !ImportValue cognitoAppClientResource
      ClientName: appClient
      GenerateSecret: true
      RefreshTokenValidity: 30
      UserPoolId: !Ref cognitoUserPool
      ReadAttributes:
        - email
      WriteAttributes:
        - email
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthScopes: !GetAtt resourceServer.AllowedScopes
      AllowedOAuthFlowsUserPoolClient: true

Outputs:
  API:
    Value: !Ref API.Stage
  CognitoData:
    Value: !Ref cognitoUserPool
    Export:
      Name: cognitoUserPool
  appClient:
    Value: !Ref appClientCustom
    Export:
      Name: CaradhrasAppClient
